#!/usr/bin/env bash
# Post-scaffold patches for the Android project generated by `flutter create`.
#   * add the INTERNET permission (release manifests don't include it, and the
#     app is useless without network access);
#   * give the app a human display name.
set -euo pipefail

MANIFEST="android/app/src/main/AndroidManifest.xml"

if [[ ! -f "$MANIFEST" ]]; then
  echo "ERROR: $MANIFEST not found (was the Android project scaffolded?)" >&2
  exit 1
fi

python3 - "$MANIFEST" <<'PY'
import re, sys
path = sys.argv[1]
xml = open(path, encoding='utf-8').read()

# 1) Ensure the INTERNET permission is present.
if 'android.permission.INTERNET' not in xml:
    xml = re.sub(
        r'(<manifest\b[^>]*>)',
        r'\1\n    <uses-permission android:name="android.permission.INTERNET"/>',
        xml, count=1)

# 2) Friendly display name.
xml = re.sub(r'android:label="[^"]*"', 'android:label="Hindukush"', xml, count=1)

open(path, 'w', encoding='utf-8').write(xml)
print("Patched", path)
PY

echo "Android manifest patched:"
grep -n "uses-permission\|android:label" "$MANIFEST" || true
